-- Job Monitor / MariaDB schema
-- Target: MariaDB 12.x
-- Character set: utf8mb4
--
-- IMPORTANT:
-- 1. Application credentials must be supplied through environment variables.
-- 2. Do not commit real passwords, tokens, or Slack webhook URLs.
-- 3. The Work24 collector writes directly to this database.

CREATE DATABASE IF NOT EXISTS job_monitor
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE job_monitor;

-- ============================================================
-- Users
-- Future multi-user support. MVP can operate with one user.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email           VARCHAR(255) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    enabled         TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_email (email),
    KEY idx_users_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Jobs
-- A normalized representation of a job listing displayed by Work24.
-- Work24 aggregates listings from multiple information providers, so
-- provider_name is kept separately from source_site.
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    -- Collection source. MVP value: WORK24
    source_site              VARCHAR(30) NOT NULL DEFAULT 'WORK24',

    -- Information provider shown by Work24 (e.g. 고용24, 잡코리아, 사람인)
    provider_name            VARCHAR(100) NULL,

    -- Identifier exposed by the source site, when available.
    external_job_id          VARCHAR(150) NULL,

    -- Stable fallback identity generated by the collector when no source ID exists.
    identity_hash            CHAR(64) NOT NULL,

    company_name             VARCHAR(255) NULL,
    title                    VARCHAR(500) NOT NULL,

    location                 VARCHAR(500) NULL,
    employment_type          VARCHAR(200) NULL,
    job_type                 VARCHAR(100) NULL,

    salary_text              VARCHAR(500) NULL,
    salary_min               DECIMAL(15,2) NULL,
    salary_max               DECIMAL(15,2) NULL,
    salary_unit              VARCHAR(30) NULL,

    career_text              VARCHAR(200) NULL,
    education_text           VARCHAR(200) NULL,

    work_days                VARCHAR(200) NULL,
    work_hours               VARCHAR(300) NULL,

    deadline                 DATE NULL,
    posted_date              DATE NULL,

    detail_url               VARCHAR(2000) NOT NULL,
    original_url             VARCHAR(2000) NULL,

    description              MEDIUMTEXT NULL,
    requirements             MEDIUMTEXT NULL,
    benefits                 MEDIUMTEXT NULL,
    qualifications           MEDIUMTEXT NULL,

    work24_application       TINYINT(1) NULL,
    company_type             VARCHAR(100) NULL,
    remote_work              TINYINT(1) NULL,
    shift_work               TINYINT(1) NULL,
    alternate_day_work       TINYINT(1) NULL,

    -- Lifecycle / collection state
    status                   VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    first_seen_at            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    closed_at                DATETIME(6) NULL,

    created_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uk_jobs_identity_hash (identity_hash),
    UNIQUE KEY uk_jobs_source_external (source_site, external_job_id),
    KEY idx_jobs_title (title(191)),
    KEY idx_jobs_company (company_name(191)),
    KEY idx_jobs_location (location(191)),
    KEY idx_jobs_deadline (deadline),
    KEY idx_jobs_posted_date (posted_date),
    KEY idx_jobs_status (status),
    KEY idx_jobs_source_provider (source_site, provider_name),
    KEY idx_jobs_first_seen (first_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Collection runs
-- One row per collector execution.
-- ============================================================
CREATE TABLE IF NOT EXISTS collection_runs (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_site              VARCHAR(30) NOT NULL,
    started_at               DATETIME(6) NOT NULL,
    finished_at              DATETIME(6) NULL,
    status                   VARCHAR(30) NOT NULL DEFAULT 'RUNNING',

    requested_pages          INT UNSIGNED NOT NULL DEFAULT 0,
    collected_count          INT UNSIGNED NOT NULL DEFAULT 0,
    inserted_count           INT UNSIGNED NOT NULL DEFAULT 0,
    updated_count            INT UNSIGNED NOT NULL DEFAULT 0,
    duplicate_count          INT UNSIGNED NOT NULL DEFAULT 0,
    error_count              INT UNSIGNED NOT NULL DEFAULT 0,

    error_message            TEXT NULL,

    PRIMARY KEY (id),
    KEY idx_collection_runs_source_started (source_site, started_at),
    KEY idx_collection_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Rules
-- MVP: keyword-based notification rules.
-- Future: richer AND/OR conditions, location, salary, schedule, etc.
-- ============================================================
CREATE TABLE IF NOT EXISTS rules (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                 BIGINT UNSIGNED NULL,
    name                    VARCHAR(100) NOT NULL,
    enabled                 TINYINT(1) NOT NULL DEFAULT 1,

    keyword_expression      TEXT NULL,
    exclude_expression      TEXT NULL,
    location_expression     TEXT NULL,

    salary_min               DECIMAL(15,2) NULL,
    salary_max               DECIMAL(15,2) NULL,

    created_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    KEY idx_rules_user_enabled (user_id, enabled),
    CONSTRAINT fk_rules_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Notification logs
-- Prevent duplicate notifications for the same rule/job/channel.
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_logs (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_id                 BIGINT UNSIGNED NOT NULL,
    job_id                  BIGINT UNSIGNED NOT NULL,
    channel                 VARCHAR(30) NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    sent_at                 DATETIME(6) NULL,
    error_message           TEXT NULL,
    created_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uk_notification_rule_job_channel (rule_id, job_id, channel),
    KEY idx_notification_job (job_id),
    KEY idx_notification_status (status),
    CONSTRAINT fk_notification_rule
        FOREIGN KEY (rule_id) REFERENCES rules(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_notification_job
        FOREIGN KEY (job_id) REFERENCES jobs(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Optional raw payload storage.
-- Disabled by default in the application design. If enabled later,
-- use it for debugging/reproducibility only and review storage/privacy
-- requirements before retaining full HTML.
-- ============================================================
CREATE TABLE IF NOT EXISTS job_raw_data (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id                  BIGINT UNSIGNED NOT NULL,
    collection_run_id       BIGINT UNSIGNED NULL,
    content_type            VARCHAR(100) NULL,
    payload                 MEDIUMTEXT NOT NULL,
    created_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    KEY idx_job_raw_job (job_id),
    KEY idx_job_raw_run (collection_run_id),
    CONSTRAINT fk_job_raw_job
        FOREIGN KEY (job_id) REFERENCES jobs(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_job_raw_run
        FOREIGN KEY (collection_run_id) REFERENCES collection_runs(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
